'''''fp = open("texto.txt","r")
datos = fp.read(16) 
print(datos)
datos = fp.read(16)
print(datos)
fp.close()
'''''
fichero = open("texto.txt","r")
linea = fichero.readlines(2)
print(linea)
linea = fichero.readlines(2)
print(linea)
linea = fichero.readlines(5)
print(linea)
fichero.close()